// ---------------------------------------------------------------------------
// Auto-curated top stories — generated by the editorial pipeline, stored in
// Supabase, and served to the homepage. Falls back to the hand-curated issue
// in lib/issues.ts when nothing has been generated yet.
// ---------------------------------------------------------------------------

import { supabase } from "@/lib/supabase";

export type AutoStory = {
  headline: string;
  url: string;
  source: string;
  category: string;
  oneliner: string; // one-sentence analyst-style take
  image: string | null;
  rank?: number;    // 1-15 from Claude; used for rolling article pool
};

export type AutoPodcast = {
  show: string;        // "The Circuit" | "Chip Stock Investor" | "Invest Like the Best"
  title: string;       // episode title (exact from RSS)
  url: string;         // episode link
  image: string | null; // show artwork or episode image from RSS
  oneliner: string;    // why semiconductor investors should listen to this specific episode
};

export type HomepageContent = {
  topStories: AutoStory[];
  podcasts: AutoPodcast[];  // one pick per show, most relevant to semi investors
  issueTitle: string; // e.g. "Week of May 26, 2026"
  generatedAt: string; // ISO timestamp
};

const TABLE = "homepage_content";
const KEY = "top_stories";

// The pipeline can emit the same article twice (e.g. picked under two
// categories). The homepage keys stories by URL, so drop repeats here.
function dedupeByUrl<T extends { url: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  return items.filter((item) => !seen.has(item.url) && seen.add(item.url));
}

export async function getHomepageContent(): Promise<HomepageContent | null> {
  try {
    const { data, error } = await supabase
      .from(TABLE)
      .select("data, generated_at")
      .eq("key", KEY)
      .single();
    if (error || !data) return null;
    const content = data.data as HomepageContent;
    return {
      ...content,
      topStories: dedupeByUrl(content.topStories ?? []),
      podcasts: dedupeByUrl(content.podcasts ?? []),
    };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Rolling article pool — homepage_articles table
// ---------------------------------------------------------------------------

const ARTICLES_TABLE = "homepage_articles";

function rowToStory(row: Record<string, unknown>): AutoStory {
  return {
    headline: row.headline as string,
    url: row.url as string,
    source: row.source as string,
    category: row.category as string,
    oneliner: row.oneliner as string,
    image: (row.image as string | null) ?? null,
    rank: row.rank as number,
  };
}

/** Read the current article pool and split into top stories + list. */
export async function getHomepageArticles(): Promise<{
  topStories: AutoStory[];
  listStories: AutoStory[];
}> {
  try {
    const { data, error } = await supabase
      .from(ARTICLES_TABLE)
      .select("*")
      .order("rank", { ascending: true });

    if (error || !data || data.length === 0) return { topStories: [], listStories: [] };

    const now = Date.now();
    const DAY_MS = 24 * 60 * 60 * 1000;

    // Shelf-life filter at READ time — guarantees expired articles never show,
    // even if the DB cleanup delete didn't run or failed:
    //   top-tier (original_rank <= 5): live for 72h
    //   lower-tier (original_rank > 5): live for 24h
    // This is what actually rotates yesterday's worst stories off the page.
    const alive = data.filter((r) => {
      const age = now - new Date(r.first_seen_at as string).getTime();
      const topTier = ((r.original_rank as number) ?? 99) <= 5;
      return age < (topTier ? 3 * DAY_MS : DAY_MS);
    });

    // Source cap: max 3 per domain across the whole page
    const sourceCounts = new Map<string, number>();
    const eligible: typeof data = [];
    for (const row of alive) {
      const src = (row.source as string).toLowerCase().trim();
      const count = sourceCounts.get(src) ?? 0;
      if (count < 3) {
        eligible.push(row);
        sourceCounts.set(src, count + 1);
      }
    }

    // Top Stories: ONLY articles first seen within the last 24h (lowest rank
    // first), up to 4. Because this keys off first_seen_at, an article can be a
    // top story for exactly one day — the day it first appears. The next run it
    // is >24h old and falls to the list below. So the same article never sits in
    // Top Stories two days in a row, and a previously-seen article can't be
    // promoted back into Top Stories.
    const topStories = eligible
      .filter((r) => now - new Date(r.first_seen_at as string).getTime() < DAY_MS)
      .slice(0, 4)
      .map(rowToStory);

    const topUrls = new Set(topStories.map((s) => s.url));

    // List: everything else still within shelf life, up to 8 (total page ≈ 12)
    const listStories = eligible
      .filter((r) => !topUrls.has(r.url as string))
      .slice(0, 8)
      .map(rowToStory);

    return { topStories, listStories };
  } catch {
    return { topStories: [], listStories: [] };
  }
}

/** Upsert today's ranked picks and expire stale articles. */
export async function saveAndExpireArticles(
  stories: AutoStory[],
): Promise<{ ok: boolean; error?: string }> {
  try {
    const now = new Date().toISOString();
    const urls = stories.map((s) => s.url);

    // Fetch existing rows to preserve first_seen_at + original_rank on update
    const { data: existing } = await supabase
      .from(ARTICLES_TABLE)
      .select("url, first_seen_at, original_rank")
      .in("url", urls);

    const existingMap = new Map(
      (existing ?? []).map((r) => [r.url as string, r]),
    );

    const rows = stories.map((s) => {
      const ex = existingMap.get(s.url);
      return {
        url: s.url,
        headline: s.headline,
        source: s.source,
        category: s.category,
        oneliner: s.oneliner,
        image: s.image ?? null,
        rank: s.rank ?? 99,
        original_rank: ex ? (ex.original_rank as number) : (s.rank ?? 99),
        first_seen_at: ex ? (ex.first_seen_at as string) : now,
        last_seen_at: now,
      };
    });

    const { error: upsertError } = await supabase
      .from(ARTICLES_TABLE)
      .upsert(rows, { onConflict: "url" });

    if (upsertError) return { ok: false, error: upsertError.message };

    // Expire stale articles. Compute which URLs are expired in JS (robust —
    // avoids the fragile PostgREST NOT-IN-with-long-URLs filter), then delete
    // with a safe .in() call. Shelf life:
    //   top-tier (original_rank <= 5): 72h
    //   lower-tier (original_rank > 5): 24h
    // Articles re-picked in this run are never expired (kept their first_seen).
    const keep = new Set(urls);
    const DAY = 24 * 60 * 60 * 1000;
    const nowMs = Date.now();

    const { data: allRows } = await supabase
      .from(ARTICLES_TABLE)
      .select("url, original_rank, first_seen_at");

    const expiredUrls = (allRows ?? [])
      .filter((r) => {
        if (keep.has(r.url as string)) return false;
        const age = nowMs - new Date(r.first_seen_at as string).getTime();
        const topTier = ((r.original_rank as number) ?? 99) <= 5;
        return age >= (topTier ? 3 * DAY : DAY);
      })
      .map((r) => r.url as string);

    if (expiredUrls.length > 0) {
      // Delete in chunks to keep the URL list well within request limits.
      for (let i = 0; i < expiredUrls.length; i += 50) {
        await supabase
          .from(ARTICLES_TABLE)
          .delete()
          .in("url", expiredUrls.slice(i, i + 50));
      }
    }

    return { ok: true };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

export async function saveHomepageContent(
  content: HomepageContent,
): Promise<{ ok: boolean; error?: string }> {
  try {
    const { error } = await supabase.from(TABLE).upsert(
      { key: KEY, data: content, generated_at: content.generatedAt },
      { onConflict: "key" },
    );
    return { ok: !error, error: error?.message };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}
