// ---------------------------------------------------------------------------
// Auto-curated top stories — generated by the editorial pipeline, stored in
// Supabase, and served to the homepage. Falls back to the hand-curated issue
// in lib/issues.ts when nothing has been generated yet.
// ---------------------------------------------------------------------------

import { supabase } from "@/lib/supabase";

export type AutoStory = {
  headline: string;
  url: string;
  source: string;
  category: string;
  oneliner: string; // one-sentence analyst-style take
  image: string | null;
};

export type AutoPodcast = {
  show: string;        // "The Circuit" | "Chip Stock Investor" | "Invest Like the Best"
  title: string;       // episode title (exact from RSS)
  url: string;         // episode link
  image: string | null; // show artwork or episode image from RSS
  oneliner: string;    // why semiconductor investors should listen to this specific episode
};

export type HomepageContent = {
  topStories: AutoStory[];
  podcasts: AutoPodcast[];  // one pick per show, most relevant to semi investors
  issueTitle: string; // e.g. "Week of May 26, 2026"
  generatedAt: string; // ISO timestamp
};

const TABLE = "homepage_content";
const KEY = "top_stories";

// The pipeline can emit the same article twice (e.g. picked under two
// categories). The homepage keys stories by URL, so drop repeats here.
function dedupeByUrl<T extends { url: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  return items.filter((item) => !seen.has(item.url) && seen.add(item.url));
}

export async function getHomepageContent(): Promise<HomepageContent | null> {
  try {
    const { data, error } = await supabase
      .from(TABLE)
      .select("data, generated_at")
      .eq("key", KEY)
      .single();
    if (error || !data) return null;
    const content = data.data as HomepageContent;
    return {
      ...content,
      topStories: dedupeByUrl(content.topStories ?? []),
      podcasts: dedupeByUrl(content.podcasts ?? []),
    };
  } catch {
    return null;
  }
}

export async function saveHomepageContent(
  content: HomepageContent,
): Promise<{ ok: boolean; error?: string }> {
  try {
    const { error } = await supabase.from(TABLE).upsert(
      { key: KEY, data: content, generated_at: content.generatedAt },
      { onConflict: "key" },
    );
    return { ok: !error, error: error?.message };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}
