// Weekly analyst summary — generated by Claude from snapshot deltas.
// Runs every Sunday via cron; stored in Supabase analyst_weekly_summary.

import Anthropic from "@anthropic-ai/sdk";
import { supabase } from "@/lib/supabase";
import { getWeeklySnapshotDeltas, type WeeklyDelta } from "./snapshots";
import { COMPANY_UNIVERSE } from "@/lib/companies";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const nameByTicker = Object.fromEntries(COMPANY_UNIVERSE.map((c) => [c.ticker, c.name]));

function fmtDelta(d: WeeklyDelta): string {
  const parts: string[] = [`${d.name} (${d.ticker})`];
  if (d.ptChangePct != null)
    parts.push(`PT ${d.ptChangePct > 0 ? "+" : ""}${d.ptChangePct.toFixed(1)}% to $${d.currentPT?.toFixed(0) ?? "?"}`);
  if (d.buyShareChange != null)
    parts.push(`buy share ${d.buyShareChange > 0 ? "+" : ""}${d.buyShareChange.toFixed(1)}pp → ${d.currentBuyShare ?? "?"}%`);
  if (d.upgrades30d > 0) parts.push(`${d.upgrades30d} upgrade${d.upgrades30d > 1 ? "s" : ""}`);
  if (d.downgrades30d > 0) parts.push(`${d.downgrades30d} downgrade${d.downgrades30d > 1 ? "s" : ""}`);
  return parts.join(" | ");
}

export async function generateWeeklySummary(): Promise<{ summary: string; highlights: WeeklyDelta[] }> {
  const deltas = await getWeeklySnapshotDeltas(nameByTicker);

  if (deltas.length === 0) {
    return {
      summary:
        "Not enough snapshot history yet to compute week-over-week changes — this section populates once daily snapshots have accumulated for at least two distinct trading days.",
      highlights: [],
    };
  }

  const top = deltas.slice(0, 8);
  const prompt = `You are a senior equity research analyst writing the "What Changed This Week" blurb for Fabuless, a semiconductor investment intelligence service read by professional investors.

Based on the analyst data below, write a single tight paragraph — 2 to 3 sentences maximum. Lead with the biggest mover. Name companies, cite actual figures. Under 60 words total.

## This Week's Analyst Moves (biggest movers first):
${top.map(fmtDelta).join("\n")}

## Date context: Week ending ${new Date().toISOString().slice(0, 10)}

Output only the paragraph — no headers, no bullets, no intro phrase like "This week...".`;

  try {
    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 80,
      messages: [{ role: "user", content: prompt }],
    });
    const summary = message.content.find((b) => b.type === "text")?.text?.trim() ?? "";
    return { summary, highlights: top };
  } catch {
    return {
      summary: "Weekly analyst summary temporarily unavailable.",
      highlights: top,
    };
  }
}

function weekKey(): string {
  // Use today's date as the key — cron runs daily, latest row wins.
  return new Date().toISOString().slice(0, 10);
}

export async function saveWeeklySummary(
  summary: string,
  highlights: WeeklyDelta[],
): Promise<{ ok: boolean }> {
  try {
    const { error } = await supabase.from("analyst_weekly_summary").upsert(
      {
        week_of: weekKey(),
        summary,
        highlights,
        generated_at: new Date().toISOString(),
      },
      { onConflict: "week_of" },
    );
    return { ok: !error };
  } catch {
    return { ok: false };
  }
}

export async function getLatestWeeklySummary(): Promise<{
  summary: string;
  week_of: string;
  highlights: WeeklyDelta[];
} | null> {
  try {
    const { data, error } = await supabase
      .from("analyst_weekly_summary")
      .select("summary, week_of, highlights")
      .order("week_of", { ascending: false })
      .limit(1)
      .single();
    if (error || !data) return null;
    return data as { summary: string; week_of: string; highlights: WeeklyDelta[] };
  } catch {
    return null;
  }
}
